// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

public static class GPGS
{
    public const string achievement_Gold1 = "CgkI-YvA8IIVEAIQAQ"; // <GPGSID>
    public const string achievement_Gold2 = "CgkI-YvA8IIVEAIQAg"; // <GPGSID>
    public const string achievement_Gold3 = "CgkI-YvA8IIVEAIQBA"; // <GPGSID>
    public const string achievement_Gold4 = "CgkI-YvA8IIVEAIQAw"; // <GPGSID>
    public const string achievement_timer1 = "CgkI-YvA8IIVEAIQBQ"; // <GPGSID>
    public const string achievement_timer2 = "CgkI-YvA8IIVEAIQBw"; // <GPGSID>
    public const string achievement_draw1 = "CgkI-YvA8IIVEAIQCA"; // <GPGSID>
    public const string achievement_draw2 = "CgkI-YvA8IIVEAIQCQ"; // <GPGSID>
    public const string achievement_draw3 = "CgkI-YvA8IIVEAIQCg"; // <GPGSID>
    public const string achievement_skin1 = "CgkI-YvA8IIVEAIQCw"; // <GPGSID>
    public const string achievement_skin2 = "CgkI-YvA8IIVEAIQDA"; // <GPGSID>
    public const string achievement_star1 = "CgkI-YvA8IIVEAIQDQ"; // <GPGSID>
    public const string achievement_star2 = "CgkI-YvA8IIVEAIQDg"; // <GPGSID>
    public const string achievement_star3 = "CgkI-YvA8IIVEAIQDw"; // <GPGSID>
    public const string achievement_star4 = "CgkI-YvA8IIVEAIQEA"; // <GPGSID>
    public const string achievement_animal1 = "CgkI-YvA8IIVEAIQEQ"; // <GPGSID>
    public const string achievement_animal2 = "CgkI-YvA8IIVEAIQEg"; // <GPGSID>
    public const string achievement_animal3 = "CgkI-YvA8IIVEAIQEw"; // <GPGSID>
    public const string LeaderBoard_star = "CgkI-YvA8IIVEAIQBg"; // 별..
    public const string LeaderBoard_Stage10 = "CgkI-YvA8IIVEAIQFA"; // 10스테이지 시간
    public const string LeaderBoard_Stage20 = "CgkI-YvA8IIVEAIQFQ"; // 20스테이지 시간
    public const string LeaderBoard_Stage30 = "CgkI-YvA8IIVEAIQFg"; // 30스테이지 시간
    public const string LeaderBoard_Stage40 = "CgkI-YvA8IIVEAIQGA"; // 40스테이지 시간
    public const string LeaderBoard_Stage50 = "CgkI-YvA8IIVEAIQFw"; // 50스테이지 시간
    public const string LeaderBoard_Stage60 = "CgkI-YvA8IIVEAIQGQ"; // 60스테이지 시간
    public const string LeaderBoard_Stage70 = "CgkI-YvA8IIVEAIQGg"; // 70스테이지 시간
    public const string LeaderBoard_Stage80 = "CgkI-YvA8IIVEAIQGw"; // 80스테이지 시간
    public const string LeaderBoard_Stage90 = "CgkI-YvA8IIVEAIQHA"; // 90스테이지 시간
    public const string LeaderBoard_Stage100 = "CgkI-YvA8IIVEAIQHQ"; // 100스테이지 시간
}
